# Generated by Django 4.2.4 on 2023-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLaboulayeNews', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.CharField(default='Laboulaye, Córdoba.', max_length=255),
            preserve_default=False,
        ),
    ]
